### ISSUE TITLE
Problem with creating image for hsa04215 KEGG pathway in ebrowser

### ISSUE THREAD

**Issue by olkap** [lgeistlinger/EnrichmentBrowser#10] opened 2018-08-08 12:52 UTC
Hi,
I would like to analyse my microarray data with EnrichmentBrowser. When I run ebrowser function, and the kegg view is being created, an error appears. Views for multiple pathways are created correctly, and an error occurs when hsa04215 is going to be created.

Below I include the sample code, in which the error is reproduced on ALL data:

```
#_________________
# Load packages
library("EnrichmentBrowser")
library("ALL")
library("hgu95av2.db")

#________________
# Load the ALL dataset

data(ALL)

#select B-cell ALL patients with and without the BCR/ABL fusion
ind.bs <- grep("^B", ALL$BT)  
ind.mut <- which(ALL$mol.biol %in% c("BCR/ABL", "NEG"))
sset <- intersect(ind.bs, ind.mut)
all.eset <- ALL[, sset]

#We compute gene expression values as the average of the corresponding probe values.
allSE <- probe2gene(all.eset) 

#______________________
# Create GROUP variable (the GROUP variable indicates whether the BCR-ABL gene fusion is present (1) or not (0).)
allSE$GROUP <- ifelse(allSE$mol.biol == "BCR/ABL", 1, 0)

#_________________
#Modify ALL dataset in order to artificially make the hsa04215 significant
gs_kegg <- getGenesets(org="hsa", db="kegg")
entrez_id = gs_kegg [["hsa04215_Apoptosis"]]
entrez_id = intersect (entrez_id, rownames(assay(allSE)))
assay(allSE)[entrez_id, allSE$GROUP == 1] = assay(allSE)[entrez_id, allSE$GROUP == 1] + 1 

#_______________
# combining results from multiple analysis methods
ebrowser( meth=c("ora"),
          exprs = allSE, 
          org="hsa", 
          data.type = "ma",
          norm.method = "none",
          gs=gs_kegg, 
          comb=TRUE, 
          nr.show=-1)

```

After running the last line of code, an error appears:
```
DE analysis ...
Execute ORA ...
100 permutations completed
200 permutations completed
300 permutations completed
400 permutations completed
500 permutations completed
600 permutations completed
700 permutations completed
800 permutations completed
900 permutations completed
1000 permutations completed
Creating gene report ...
Creating set view ...
Creating kegg view ...
Loading required package: pathview
Info: Downloading xml files for hsa04215, 1/1 pathways..
Info: Downloading png files for hsa04215, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/
Info: Writing image file hsa04215.kpath.png
Info: some node width is different from others, and hence adjusted!
Error in img[pidx[i, 3]:pidx[i, 4], sel.px, 1:3] : 
  only 0's may be mixed with negative subscripts
```

sessionInfo():
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] pathview_1.20.0             bindrcpp_0.2.2              hgu95av2.db_3.2.3           org.Hs.eg.db_3.6.0         
 [5] AnnotationDbi_1.42.1        ALL_1.22.0                  EnrichmentBrowser_2.10.7    graph_1.58.0               
 [9] SummarizedExperiment_1.10.1 DelayedArray_0.6.4          BiocParallel_1.14.2         matrixStats_0.54.0         
[13] Biobase_2.40.0              GenomicRanges_1.32.6        GenomeInfoDb_1.16.0         IRanges_2.14.10            
[17] S4Vectors_0.18.3            BiocGenerics_0.26.0        

loaded via a namespace (and not attached):
  [1] backports_1.1.2          GOstats_2.46.0           circlize_0.4.4           Hmisc_4.1-1             
  [5] BiocFileCache_1.4.0      plyr_1.8.4               lazyeval_0.2.1           GSEABase_1.42.0         
  [9] splines_3.5.1            ggplot2_3.0.0            digest_0.6.15            BiocInstaller_1.30.0    
 [13] ensembldb_2.4.1          htmltools_0.3.6          GO.db_3.6.0              magrittr_1.5            
 [17] checkmate_1.8.5          memoise_1.1.0            BSgenome_1.48.0          cluster_2.0.7-1         
 [21] limma_3.36.2             ComplexHeatmap_1.18.1    Biostrings_2.48.0        annotate_1.58.0         
 [25] R.utils_2.6.0            ggbio_1.28.4             prettyunits_1.0.2        colorspace_1.3-2        
 [29] blob_1.1.1               rappdirs_0.3.1           dplyr_0.7.6              crayon_1.3.4            
 [33] RCurl_1.95-4.11          genefilter_1.62.0        bindr_0.1.1              survival_2.42-6         
 [37] VariantAnnotation_1.26.1 glue_1.3.0               gtable_0.2.0             zlibbioc_1.26.0         
 [41] XVector_0.20.0           GetoptLong_0.1.7         Rgraphviz_2.24.0         shape_1.4.4             
 [45] SparseM_1.77             scales_0.5.0             DBI_1.0.0                GGally_1.4.0            
 [49] edgeR_3.22.3             Rcpp_0.12.18             xtable_1.8-2             progress_1.2.0          
 [53] htmlTable_1.12           foreign_0.8-71           bit_1.1-14               OrganismDbi_1.22.0      
 [57] Formula_1.2-3            AnnotationForge_1.22.2   htmlwidgets_1.2          httr_1.3.1              
 [61] RColorBrewer_1.1-2       acepack_1.4.1            pkgconfig_2.0.1          reshape_0.8.7           
 [65] XML_3.98-1.13            R.methodsS3_1.7.1        nnet_7.3-12              dbplyr_1.2.2            
 [69] locfit_1.5-9.1           tidyselect_0.2.4         rlang_0.2.1              reshape2_1.4.3          
 [73] munsell_0.5.0            tools_3.5.1              RSQLite_2.1.1            stringr_1.3.1           
 [77] knitr_1.20               bit64_0.9-7              purrr_0.2.5              KEGGREST_1.20.1         
 [81] AnnotationFilter_1.4.0   RBGL_1.56.0              R.oo_1.22.0              KEGGgraph_1.40.0        
 [85] biomaRt_2.36.1           compiler_3.5.1           rstudioapi_0.7           curl_3.2                
 [89] png_0.1-7                PFAM.db_3.6.0            tibble_1.4.2             geneplotter_1.58.0      
 [93] stringi_1.1.7            GenomicFeatures_1.32.0   lattice_0.20-35          ProtGenerics_1.12.0     
 [97] Matrix_1.2-14            pillar_1.3.0             GlobalOptions_0.1.0      data.table_1.11.4       
[101] bitops_1.0-6             rtracklayer_1.40.3       R6_2.2.2                 latticeExtra_0.6-28     
[105] hwriter_1.3.2            gridExtra_2.3            dichromat_2.0-0          assertthat_0.2.0        
[109] DESeq2_1.20.0            Category_2.46.0          rjson_0.2.20             ReportingTools_2.20.0   
[113] safe_3.20.0              GenomicAlignments_1.16.0 Rsamtools_1.32.2         GenomeInfoDbData_1.1.0  
[117] hms_0.4.2                grid_3.5.1               rpart_4.1-13             biovizBase_1.28.1       
[121] base64enc_0.1-3  
```

**Comment by jdrnevich** [comment] 2018-08-08 13:46
I just had this same error with some mouse data, but hadn't had a chance to see if I could get a reproducible example with the human data. Interestingly, it is the same pathway:

`Info: Working in directory D:/Statistics/Boppart/2018-Jun-RNASeq`
`Info: Writing image file mmu04215.kpath.png`
`Info: some node width is different from others, and hence adjusted!`
`  Error in img[pidx[i, 3]:pidx[i, 4], sel.px, 1:3] :`
`  only 0's may be mixed with negative subscripts`

We also found another pathway, mmu04723, that caused the same error. This might be a problem inherent to the KEGG pathways, but I didn't have time to dig into it. Our workaround was to simple remove these two pathways from the Gene set and then the report would be generated so we could see the other pathways:

`kegg.gs <- getGenesets(org="mmu", db="kegg")`
`#Using cached version from 2018-07-31 19:10:42`

`length(kegg.gs) #325`
`#remove mmu04215 entry because it will causing pathwayview pop an error`
`kegg.gs[grep("mmu04215", names(kegg.gs))]`
`kegg.gs <- kegg.gs[-grep("mmu04215", names(kegg.gs))]`
`kegg.gs <- kegg.gs[-grep("mmu04723", names(kegg.gs))]`
`length(kegg.gs)`

**Comment by jdrnevich** [comment] 2018-08-08 14:11
Update: two old posts on Bioconductor about this issue with pathview, although no solutions posted:
https://support.bioconductor.org/p/90506/
https://support.bioconductor.org/p/93109/

**Comment by lgeistlinger** [comment] 2018-08-08 14:19
Yes, this has been reported before and I have also contacted the pathview maintainer on this (without response).
The workaround from Jenny is what I also typically suggest.

I'm going to soon introduce a catch for the case pathview fails.

**Comment by jdrnevich** [comment] 2018-08-08 14:37
A catch would be great - the first time when we had to download all the pathways, it ran for ~30 min before just hitting the pathview error and nothing to show for it!

**Comment by olkap** [comment] 2018-08-08 15:04
Thank you for the fast answer. 
Indeed, it would be great if the EnrichmentBrowser analysed that particular pathway but just omited the generation of the view of that pathway.

**Comment by lgeistlinger** [comment] 2018-08-10 16:42
This is fixed in EnrichmentBrowser v2.10.9:

http://bioconductor.org/packages/EnrichmentBrowser

Thanks a lot for working out the illustrative example @olkap!

It's a bit weird anyhow, apparently KEGG has a new cross-species Apoptosis pathway (https://www.genome.jp/kegg-bin/show_pathway?map=hsa04215&show_description=show) in addition to the canonical human Apoptosis pathway (https://www.genome.jp/kegg-bin/show_pathway?map=hsa04210&show_description=show), so you are ending up with almost a duplicate in the enrichment analysis.

**Comment by olkap** [comment] 2018-08-13 14:16
It works now, thank you.

**Closed as completed** 2018-08-13 14:22 UTC
Labels: bug

**Comment by lizhan96** [comment] 2022-10-14 06:33
> It works now, thank you.

hello. Could you offer the code that solving this problem?

**Comment by SAADAT-Abu** [comment] 2023-02-28 14:58
In pathview KEGG visualization, setting "same.layer" to FALSE fixed the problem for me.
